-- 由 SYS 在同一個 FREEPDB1 讀取 MEDSUPPLY 已執行游標的 ALLSTATS LAST。
-- DISPLAY_CURSOR 本身會讀 V$ 檢視；以 SYS 顯示可避免長駐提高應用帳號權限。
SET SQLBLANKLINES ON
SET LINESIZE 220
SET PAGESIZE 1000
SET LONG 100000
SET LONGCHUNKSIZE 100000
SET TRIMSPOOL ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

ALTER SESSION SET CONTAINER = FREEPDB1;

COLUMN before_sql_id NEW_VALUE beforeSqlId NOPRINT
SELECT sql_id AS before_sql_id
FROM (
    SELECT sql_id
    FROM v$sql
    WHERE parsing_schema_name = 'MEDSUPPLY'
      AND sql_text LIKE '%WO_D_FEFO_BEFORE%'
    ORDER BY last_active_time DESC
)
WHERE ROWNUM = 1;

PROMPT BEFORE_INDEX_INVISIBLE_AND_FULL_HINT_PLAN
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR('&beforeSqlId', NULL, 'ALLSTATS LAST'));

COLUMN after_sql_id NEW_VALUE afterSqlId NOPRINT
SELECT sql_id AS after_sql_id
FROM (
    SELECT sql_id
    FROM v$sql
    WHERE parsing_schema_name = 'MEDSUPPLY'
      AND sql_text LIKE '%WO_D_FEFO_AFTER%'
    ORDER BY last_active_time DESC
)
WHERE ROWNUM = 1;

PROMPT AFTER_INDEX_VISIBLE_PLAN
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR('&afterSqlId', NULL, 'ALLSTATS LAST'));
