-- 顯示儀表板讀取路徑基準四個已執行 cursor 的完整 ALLSTATS LAST；由 SYS 讀 V$SQL / DBMS_XPLAN。
SET LINESIZE 220
SET PAGESIZE 1000
SET LONG 100000
SET LONGCHUNKSIZE 100000
SET TRIMSPOOL ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

ALTER SESSION SET CONTAINER = FREEPDB1;

COLUMN sql_id NEW_VALUE plan_sql_id NOPRINT

PROMPT === AUDIT_BASELINE_RUN_1 ===
SELECT sql_id FROM (SELECT sql_id FROM v$sql WHERE sql_text LIKE '%WO_S_AUDIT_' || 'BASELINE_RUN_1%' ORDER BY last_active_time DESC) WHERE ROWNUM = 1;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR('&plan_sql_id', NULL, 'ALLSTATS LAST'));

PROMPT === AUDIT_BASELINE_RUN_2 ===
SELECT sql_id FROM (SELECT sql_id FROM v$sql WHERE sql_text LIKE '%WO_S_AUDIT_' || 'BASELINE_RUN_2%' ORDER BY last_active_time DESC) WHERE ROWNUM = 1;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR('&plan_sql_id', NULL, 'ALLSTATS LAST'));

PROMPT === EXPIRED_BASELINE_RUN_1 ===
SELECT sql_id FROM (SELECT sql_id FROM v$sql WHERE sql_text LIKE '%WO_S_EXPIRED_' || 'BASELINE_RUN_1%' ORDER BY last_active_time DESC) WHERE ROWNUM = 1;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR('&plan_sql_id', NULL, 'ALLSTATS LAST'));

PROMPT === EXPIRED_BASELINE_RUN_2 ===
SELECT sql_id FROM (SELECT sql_id FROM v$sql WHERE sql_text LIKE '%WO_S_EXPIRED_' || 'BASELINE_RUN_2%' ORDER BY last_active_time DESC) WHERE ROWNUM = 1;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR('&plan_sql_id', NULL, 'ALLSTATS LAST'));
