-- 顯示 V007 套用後的四個 cursor；拆開 marker 字串，避免本顯示 SQL 自我匹配。
SET LINESIZE 220
SET PAGESIZE 1000
SET LONG 100000
SET LONGCHUNKSIZE 100000
SET TRIMSPOOL ON
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

ALTER SESSION SET CONTAINER = FREEPDB1;

COLUMN sql_id NEW_VALUE plan_sql_id NOPRINT

PROMPT === AUDIT_INDEXED_RUN_1 ===
SELECT sql_id FROM (SELECT sql_id FROM v$sql WHERE sql_text LIKE '%WO_S_AUDIT_' || 'INDEXED_RUN_1%' ORDER BY last_active_time DESC) WHERE ROWNUM = 1;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR('&plan_sql_id', NULL, 'ALLSTATS LAST'));

PROMPT === AUDIT_INDEXED_RUN_2 ===
SELECT sql_id FROM (SELECT sql_id FROM v$sql WHERE sql_text LIKE '%WO_S_AUDIT_' || 'INDEXED_RUN_2%' ORDER BY last_active_time DESC) WHERE ROWNUM = 1;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR('&plan_sql_id', NULL, 'ALLSTATS LAST'));

PROMPT === EXPIRED_INDEXED_RUN_1 ===
SELECT sql_id FROM (SELECT sql_id FROM v$sql WHERE sql_text LIKE '%WO_S_EXPIRED_' || 'INDEXED_RUN_1%' ORDER BY last_active_time DESC) WHERE ROWNUM = 1;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR('&plan_sql_id', NULL, 'ALLSTATS LAST'));

PROMPT === EXPIRED_INDEXED_RUN_2 ===
SELECT sql_id FROM (SELECT sql_id FROM v$sql WHERE sql_text LIKE '%WO_S_EXPIRED_' || 'INDEXED_RUN_2%' ORDER BY last_active_time DESC) WHERE ROWNUM = 1;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY_CURSOR('&plan_sql_id', NULL, 'ALLSTATS LAST'));
